const colors = {
  light: {
    text:                  "#FFFFFF",
    tint:                  "#00D9A0",
    background:            "#0A0A0F",
    foreground:            "#FFFFFF",
    surface:               "#14141F",
    card:                  "#1C1C2A",
    cardForeground:        "#FFFFFF",
    primary:               "#00D9A0",
    primaryForeground:     "#0A0A0F",
    secondary:             "#14141F",
    secondaryForeground:   "#FFFFFF",
    muted:                 "#14141F",
    mutedForeground:       "#8F8FA3",
    accent:                "#00D9A0",
    accentForeground:      "#0A0A0F",
    accentDim:             "rgba(0,217,160,0.12)",
    accentGlow:            "rgba(0,217,160,0.22)",
    destructive:           "#FF5B7A",
    destructiveForeground: "#FFFFFF",
    destructiveDim:        "rgba(255,91,122,0.12)",
    border:                "#2A2A3D",
    input:                 "#1C1C2A",
    inputBorder:           "#2A2A3D",
    inputFocus:            "#00D9A0",
    success:               "#00D9A0",
    successLight:          "rgba(0,217,160,0.12)",
    warning:               "#F59E0B",
    warningLight:          "rgba(245,158,11,0.14)",
    overlay:               "rgba(0,0,0,0.7)",
    placeholder:           "#55556A",
    subtitle:              "#8F8FA3",
  },
  radius: 14,
};

export default colors;
