const colors = {
  light: {
    text:                  "#0B0A0A",
    tint:                  "#35C2C1",
    background:            "#FFFFFF",
    foreground:            "#0B0A0A",
    surface:               "#F7F8F9",
    card:                  "#FFFFFF",
    cardForeground:        "#0B0A0A",
    primary:               "#35C2C1",
    primaryForeground:     "#FFFFFF",
    secondary:             "#F7F8F9",
    secondaryForeground:   "#0B0A0A",
    muted:                 "#F7F8F9",
    mutedForeground:       "#8391A1",
    accent:                "#35C2C1",
    accentForeground:      "#FFFFFF",
    accentDim:             "rgba(53,194,193,0.12)",
    accentGlow:            "rgba(53,194,193,0.22)",
    destructive:           "#FF5B7A",
    destructiveForeground: "#FFFFFF",
    destructiveDim:        "rgba(255,91,122,0.12)",
    border:                "#E8ECF4",
    input:                 "#F7F8F9",
    inputBorder:           "#E8ECF4",
    inputFocus:            "#35C2C1",
    success:               "#00B03C",
    successLight:          "rgba(0,176,60,0.12)",
    warning:               "#F59E0B",
    warningLight:          "rgba(245,158,11,0.14)",
    overlay:               "rgba(0,0,0,0.5)",
    placeholder:           "#8391A1",
    subtitle:              "#6A707C",
  },
  radius: 14,
};

export default colors;
