// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/UserDashBoard.tsx": () => import("../components/mockups/UserDashBoard.tsx"),
  "./components/mockups/VirtualCardScreen.tsx": () => import("../components/mockups/VirtualCardScreen.tsx")
};
